#!/usr/bin/env bash

# Additional R Packages
sudo su - -c "R -e \"install.packages('tidyverse', version='1.3.2', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('dplyr', version='1.1.0', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('tidyr', version='1.3.0', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('ggplot2', version='3.4.1', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('data.table', version='1.14.6', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('httpuv', version='1.6.9', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('devtools', version='2.4.5', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('kableExtra', version='1.3.4', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('survival', version='3.5.3', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('survminer', version='0.4.9', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('MASS', version='7.3.58.2', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('quantreg', version='5.94', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('DescTools', version='0.99.47', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('rentrez', version='1.2.3', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('XML', version='3.99.0.13', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('Matrix', version='1.5.3', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('irlba', version='2.3.5.1', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('threejs', version='0.3.3', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('seqinr', version='4.2.23', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('adegenet', version='2.1.10', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('urltools', version='1.7.3', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('bitops', version='1.0.7', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('maptools', version='1.1.6', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('randomForest', version='4.7.1.1', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"install.packages('RCurl', version='1.98.1.10', repos='http://cran.r-project.org/')\""
sudo su - -c "R -e \"remotes::install_github('YuLab-SMU/ggtree', version='3.7.1.2', dep=TRUE)\""
